<a href="https://colab.research.google.com/github/poudyaldiksha/Data-Science-project/blob/main/Lesson_17_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 17: Pandas DataFrame

In the last class, we learned about the Pandas Series. Now, in this lesson, we will learn about Pandas DataFrame, which is a collection of Pandas Series. In other words, a Pandas DataFrame is a two-dimensional array.

In the process of learning Pandas DataFrames, we will explore how NASA finds exoplanets in the universe. While there are deep physical and mathematical theories behind this, we'll focus on the basic principles to learn how exoplanets are discovered.


### Activity 1:  Creating DataFrame using different approaches
In this activity, we will learn how to create a DataFrame using different methods in Pandas. These methods include creating a DataFrame from a dictionary, a list of lists, and from an existing CSV file.

A DataFrame is essentially a table of data with rows and columns. Each column in a DataFrame is a Pandas Series. So we can also say  Pandas DataFrame is a collection of Pandas series. In other words, a Pandas DataFrame is a two-dimensional array.

Data in Frame(Rows and Columns)

To understand DataFrames better, we will use a dataset that records the heights and weights of individuals.

**Creating Empty DataFrame**

In [ ]:
#Example
import pandas as pd
e_df = pd.DataFrame( )
print(e_df)

Empty DataFrame
Columns: []
Index: []

**1. Creating a DataFrame from a Dictionary**

One common way to create a DataFrame is by using a dictionary. Each key in the dictionary represents a column name, and the corresponding value is a list of values for that column.

In [ ]:
# Creating a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

# Creating a DataFrame from the dictionary
df_dict = pd.DataFrame(data)
print(df_dict)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [ ]:
b = pd.Series([1,2,3])
b

0    1
1    2
2    3
dtype: int64

In [ ]:
a = pd.DataFrame([1,2,3])
a

   0
0  1
1  2
2  3

In [ ]:
type(a)

pandas.core.frame.DataFrame

In [ ]:
df_dict.shape

(4, 3)

In [ ]:
df_dict.shape[1]

3

**2. Creating a DataFrame from a List of Lists**

Another way to create a DataFrame is by using a list of lists. In this approach, each inner list represents a row of data, and we can specify the column names separately.

In [ ]:

# Creating a list of lists
data = [
    ['Alice', 24, 'New York'],
    ['Bob', 27, 'Los Angeles'],
    ['Charlie', 22, 'Chicago'],
    ['David', 32, 'Houston']
]

# Creating a DataFrame from the list of lists
df_list = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df_list)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [ ]:
# Creating a list of lists
data = [
    ['Alice', 24, 'New York'],
    ['Bob', 27, 'Los Angeles'],
    ['Charlie', 22, 'Chicago'],
    ['David', 32, 'Houston']
]

# Creating a DataFrame from the list of lists
df_list = pd.DataFrame(data
)
print(df_list)

         0   1            2
0    Alice  24     New York
1      Bob  27  Los Angeles
2  Charlie  22      Chicago
3    David  32      Houston

**3. Creating a DataFrame from an Existing CSV File**

One of the most common ways to create a DataFrame is by reading data from a CSV file using the `read_csv()` function.

In [ ]:
# create dataframe from csv file
df = pd.read_csv("/content/hw_200.csv")
df

###Activity 2: Checking for Missing Values

Use the `isnull()` function to check for missing values in the DataFrame. Display the total number of missing values in each column.

In [ ]:
#activity

###Activity 3: Slicing a DataFrame Using the `iloc[]` Function

Extract specific rows and columns from the DataFrame using the` iloc[]` function.

The **iloc** indexer in Pandas is a powerful tool used to select rows and columns from a DataFrame by their integer position (i.e., their index position). It stands for "integer location" and allows for both row and column indexing.

**Syntax:**

`dataframe_name.iloc[row_position_start : row_position_end, column_position_start : column_position_end]`

In this syntax:

- `row_position_start` denotes the position of the row in the DataFrame **starting** from whose values you want to take in the new Pandas series or DataFrame.
- `row_position_end` denotes the position of the row in the DataFrame till whose values you want to take in the new Pandas series or DataFrame.
- `column_position_start` denotes the position of the column in the DataFrame **starting** from whose values you want to take in the new Pandas series or DataFrame.
- `column_position_end` denotes the position of the column in the DataFrame till whose values you want to take in the new Pandas series or DataFrame.

In [ ]:
# Create a simple DataFrame
data = {'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8],
        'C': [9, 10, 11, 12]}
df = pd.DataFrame(data)

print(df)

In [ ]:
w=df.iloc[0]

In [ ]:
df.iloc[0:3]

In [ ]:
q=df.iloc[0:3,0:2]

In [ ]:
df.iloc[:,0:2]

In [ ]:
df.iloc[[0,2,3],[1,2]]

## About Dataset

**Finding Exoplanets Principle**



NASA placed the Kepler telescope in space to measure the brightness of stars in distant galaxies. When a planet passes between the telescope and a star, the recorded brightness decreases. When the planet moves behind the star, the brightness increases. This method of detecting exoplanets through the brightness of the light emitted by a star is called the Transit Method.

When plotting brightness (vertical axis) against time (horizontal axis), the brightness of the star recorded by the telescope shows a wave-like pattern, indicating the presence of at least one planet.

### Activity 1: Loading a CSV File
We store data in various formats such as text (txt), comma-separated value (csv), tab-separated value (tsv), etc. We can read the contents of these files using Python. The most common format is the csv file.

To load or read a csv file, we use the `read_csv()` function in Pandas. The data is read as a two-dimensional array called a Pandas DataFrame.

As an input to the `read_csv()` function, we need to provide the full-location of the `csv` file that we wish to read in the string format. The file that we wish to read is stored in cloud storage.

Dataset Source: https://www.kaggle.com/datasets/keplersmachines/kepler-labelled-time-series-data

In [ ]:
pd.read_csv("/content/hw_200.csv")

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

In [ ]:
import pandas as pd
df2 = pd.read_csv("/content/hw_200.csv")
df2.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
import pandas as pd

exo_train_df=pd.read_csv("/content/drive/MyDrive/datasets/exoTrain.csv")
exo_train_df.head()

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
0,2,93.85,83.81,20.10,-26.98,-39.56,-124.71,-135.18,-96.27,-79.89,...,-78.07,-102.15,-102.15,25.13,48.57,92.54,39.32,61.42,5.08,-39.54
1,2,-38.88,-33.83,-58.54,-40.09,-79.31,-72.81,-86.55,-85.33,-83.97,...,-3.28,-32.21,-32.21,-24.89,-4.86,0.76,-11.70,6.46,16.00,19.93
2,2,532.64,535.92,513.73,496.92,456.45,466.00,464.50,486.39,436.56,...,-71.69,13.31,13.31,-29.89,-20.88,5.06,-11.80,-28.91,-70.02,-96.67
3,2,326.52,347.39,302.35,298.13,317.74,312.70,322.33,311.31,312.42,...,5.71,-3.73,-3.73,30.05,20.03,-12.67,-8.77,-17.31,-17.35,13.98
4,2,-1107.21,-1112.59,-1118.95,-1095.10,-1057.55,-1034.48,-998.34,-1022.71,-989.57,...,-594.37,-401.66,-401.66,-357.24,-443.76,-438.54,-399.71,-384.65,-411.79,-510.54

In [ ]:
exo_train_df.tail(3)

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
5084,1,273.39,278.00,261.73,236.99,280.73,264.90,252.92,254.88,237.60,...,-26.82,-53.89,-48.71,30.99,15.96,-3.47,65.73,88.42,79.07,79.43
5085,1,3.82,2.09,-3.29,-2.88,1.66,-0.75,3.85,-0.03,3.28,...,10.86,-3.23,-5.10,-4.61,-9.82,-1.50,-4.65,-14.55,-6.41,-2.55
5086,1,323.28,306.36,293.16,287.67,249.89,218.30,188.86,178.93,118.93,...,71.19,0.97,55.20,-1.63,-5.50,-25.33,-41.31,-16.72,-14.09,27.82

In [ ]:
exo_train_df.shape

(5087, 3198)

Now, you create a DataFrame for the exoTest.csv file and store it in a variable called exo_test_df.

In [ ]:
exo_test_df=pd.read_csv("/content/drive/MyDrive/datasets/exoTest.csv")
exo_test_df.head()

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
0,2,119.88,100.21,86.46,48.68,46.12,39.39,18.57,6.98,6.63,...,14.52,19.29,14.44,-1.62,13.33,45.50,31.93,35.78,269.43,57.72
1,2,5736.59,5699.98,5717.16,5692.73,5663.83,5631.16,5626.39,5569.47,5550.44,...,-581.91,-984.09,-1230.89,-1600.45,-1824.53,-2061.17,-2265.98,-2366.19,-2294.86,-2034.72
2,2,844.48,817.49,770.07,675.01,605.52,499.45,440.77,362.95,207.27,...,17.82,-51.66,-48.29,-59.99,-82.10,-174.54,-95.23,-162.68,-36.79,30.63
3,2,-826.00,-827.31,-846.12,-836.03,-745.50,-784.69,-791.22,-746.50,-709.53,...,122.34,93.03,93.03,68.81,9.81,20.75,20.25,-120.81,-257.56,-215.41
4,2,-39.57,-15.88,-9.16,-6.37,-16.13,-24.05,-0.90,-45.20,-5.04,...,-37.87,-61.85,-27.15,-21.18,-33.76,-85.34,-81.46,-61.98,-69.34,-17.84

In [ ]:
exo_test_df

,LABEL,FLUX.1,FLUX.2,FLUX.3,FLUX.4,FLUX.5,FLUX.6,FLUX.7,FLUX.8,FLUX.9,...,FLUX.3188,FLUX.3189,FLUX.3190,FLUX.3191,FLUX.3192,FLUX.3193,FLUX.3194,FLUX.3195,FLUX.3196,FLUX.3197
0,2,119.88,100.21,86.46,48.68,46.12,39.39,18.57,6.98,6.63,...,14.52,19.29,14.44,-1.62,13.33,45.50,31.93,35.78,269.43,57.72
1,2,5736.59,5699.98,5717.16,5692.73,5663.83,5631.16,5626.39,5569.47,5550.44,...,-581.91,-984.09,-1230.89,-1600.45,-1824.53,-2061.17,-2265.98,-2366.19,-2294.86,-2034.72
2,2,844.48,817.49,770.07,675.01,605.52,499.45,440.77,362.95,207.27,...,17.82,-51.66,-48.29,-59.99,-82.10,-174.54,-95.23,-162.68,-36.79,30.63
3,2,-826.00,-827.31,-846.12,-836.03,-745.50,-784.69,-791.22,-746.50,-709.53,...,122.34,93.03,93.03,68.81,9.81,20.75,20.25,-120.81,-257.56,-215.41
4,2,-39.57,-15.88,-9.16,-6.37,-16.13,-24.05,-0.90,-45.20,-5.04,...,-37.87,-61.85,-27.15,-21.18,-33.76,-85.34,-81.46,-61.98,-69.34,-17.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,1,374.46,326.06,319.87,338.23,251.54,209.84,186.35,167.46,135.45,...,-123.55,-166.90,-222.44,-209.71,-180.16,-166.83,-235.66,-213.63,-205.99,-194.07
566,1,-0.36,4.96,6.25,4.20,8.26,-9.53,-10.10,-4.54,-11.55,...,-12.40,-5.99,-17.94,-11.96,-12.11,-13.68,-3.59,-5.32,-10.98,-11.24
567,1,-54.01,-44.13,-41.23,-42.82,-39.47,-24.88,-31.14,-24.71,-13.12,...,-0.73,-1.64,1.58,-4.82,-11.93,-17.14,-4.25,5.47,14.46,18.70
568,1,91.36,85.60,48.81,48.69,70.05,22.30,11.63,37.86,28.27,...,2.44,11.53,-16.42,-17.86,21.10,-10.25,-37.06,-8.43,-6.48,17.60
569,1,3071.19,2782.53,2608.69,2325.47,2089.37,1769.56,1421.09,1142.09,902.31,...,695.41,865.97,882.41,1203.06,1293.03,1354.41,-192.81,-277.22,-69.63,121.56

### Activity 2: Check for Missing Values
Datasets often have missing values or non-standardized values. Before analysis, check for missing values using the `isnull() `function.

In [ ]:
#Activity: Check for missing values.

To simplify, we sum the True values in each column. If a column has no missing values, the sum is 0.

### Activity 3: Shape,columns keywords

In [ ]:
# Activity

In [ ]:
#activity

### Activity 4: Slicing a DataFrame Using the `iloc[]` Function
We will plot scatter and line plots for few stars. For each star, create a Pandas Series of brightness levels from FLUX.1 to FLUX.3197.

In [ ]:
#Create a Pandas series from a Pandas DataFrame using the 'iloc[]' function.
star0=exo_train_df.iloc[0,:]
star0

In [ ]:
# Using the 'iloc[]' function, create a Pandas series for the second star and store it in a variable called 'star1'.
star1=exo_train_df.iloc[1,:]
star1

In [ ]:
# Using the 'iloc[]' function, create a Pandas series for the second star and store it in a variable called 'star2'.
star2 =exo_train_df.iloc[2,:]
star2.head()

In [ ]:
#Using the 'iloc[]' function, create a Pandas series for the last star and store it in a variable called 'star5086'
star5086 = exo_train_df.iloc[5086, :]
star5086.head()

In [ ]:
#Using the 'iloc[]' function, create a Pandas series for the third-last star and store it in a variable called 'star5084'
star5085 = exo_train_df.iloc[5085, :]
star5085.head()

`pd.set_option('display.max_rows', None)` It will display all rows


### Activity 5: Scatter And Line Plots

In this activity, we will create scatter and line plots to visualize the brightness levels of stars. Follow the steps below to generate these plots.

To make this plot,

1. Import the necessary library:
First, we need to import the matplotlib.pyplot module, commonly used for creating a variety of plots, including scatter and line plots.


  ```
  import matplotlib.pyplot as plt
  ```

2. Set the figure size: To resize the plot, we use the `figure()` function from plt, specifying the desired width and height.



  ```
  plt.figure(figsize=(16, 4))
  ```

3. Generate x-values: We need an array of numbers from 1 to 3197 for the x-axis. This can be achieved using a NumPy array, a Python list, or a Pandas Series.
  ```
  x_values_star_0 = np.arange(1, 3198)

  ```

4. Extract y-values: For the y-axis, we will use the FLUX values from the star_0 Pandas Series, excluding the first column.



  ```
  y_values_star_0 = star0[1:]
  ```

5. Create the scatter plot: We use the `scatter()` function from plt to plot the data points, providing the x-values and y-values.

  ```
  plt.scatter(x_values_star_0, y_values_star_0)
  ```

6. Display the plot:Finally, to render the plot, we call the `show()` function.

  ```
  plt.show()
  ```

In [ ]:
# Activity.

#Step 1: import
import matplotlib.pyplot as plt
import numpy as np
# Step 2: Set the figure size
plt.figure(figsize = (15,5))

# Step 3: Generate x-values
x_values = np.arange(1,3198)

# Step 4: Extract y-values
y_values = star0[1:]

# Step 5: Create the scatter plot
plt.scatter(x_values,y_values, marker = "*")

# Step 6: Display the plot
plt.show()


Let's draw the line plot also to see this fluctuation in a different manner.

To draw a line plot, you have to follow the same steps that you followed to create a scatter plot except in the fifth step, you have to call the `plot()` function instead of the `scatter()` function from the `plt` module.

In [ ]:
# Line plot for the first star in the DataFrame.

plt.figure(figsize=(15,5))
plt.plot(x_values,y_values,color = "green",linewidth = 1, linestyle = "dashed")
plt.title("star_0 flux values")
plt.xlabel("number of observations")
plt.ylabel("flux values")
plt.show()

In [ ]:
# Create a scatter plot for the second star,'star1'.
plt.figure(figsize=(50,4))
plt.scatter(np.arange(1,3198),star1[1:])
plt.show()

In [ ]:
# Create a line plot for the second star,'star1'.
plt.figure(figsize=(20,4))
plt.plot(np.arange(1,3198),star1[1:])
plt.show()

### Activity 6: Scatter Plots And Line Plots For Last 2 Stars
Now, let's create the scatter plots and line plots for the last three stars in the DataFrame which have been labelled or classified as `1`.

In [ ]:
# Create a scatter plot for the last star, 'star5086' in the DataFrame.
plt.figure(figsize=(50,5))
plt.scatter(np.arange(1,3198), star5086[1:], marker="^")
plt.show()

As you can see, there is no clear periodic downward-peak in the brightness levels of the light emitted from the star.

In [ ]:
#Create a line plot for the last star,'star5086' in the DataFrame.
plt.figure(figsize=(20,5))
plt.plot(np.arange(1,3198), star5086[1:])
plt.show()

There are some sudden spikes in the line plot but they exist at irregular intervals. So we cannot say for sure that the star has a planet.

In [ ]:
#Create a scatter plot for the second-last star, i.e., 'star5085' in the DataFrame.
plt.figure(figsize=(24,8))
plt.scatter(np.arange(1,3198), star5085[1:])
plt.show()

In [ ]:
#Create a line plot for the second-last star in the DataFrame.
plt.figure(figsize=(24,8))
plt.plot(np.arange(1,3198), star5085[1:])
plt.show()

### Activity 7: Column Operations In pandas dataframe

#### Renaming columns
**Rename a Single Column:** To rename a single column, use the rename method.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

In [ ]:
df.rename(columns={'city': 'city_name'})
print(df)

**Rename Multiple Columns:** To rename multiple columns, specify each column in the dictionary.

In [ ]:

df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

In [ ]:
df.rename(columns={'city': 'city_name', 'population': 'population_count'}, inplace=True)
print(df)

### Activity 8: Apply function to column names
**Make All Column Names Uppercase:**
You can convert all column names to uppercase using list comprehension.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df.columns = [col.upper() for col in df.columns]
print(df)

          CITY  POPULATION
0     New York     8175133
1  Los Angeles     3792621
2      Chicago     2695598

### Activity 9: Applying Functions to Column Data


**Convert Column Values to Uppercase:**
Use the map function to apply a lambda function to a column.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df['city'] = df['city'].map(lambda city: city.upper())
print(df)

**Key Points:**

- **Map** is a built-in function in Python that allows you to iterate over an iterable (like a list or column in a DataFrame) and apply a function to each element.
- **Lambda** functions provide a way to define small, anonymous functions in Python without the need for a separate def statement. They are especially useful when you need a short, one-line function for a specific task within another function like map.

### Activity 10: Creating Derived Columns
**Add a New Column Based on Existing Data:**
You can create new columns using existing data in the DataFrame.And it's very common to add new columns using derived data. You just need to assign to a new column:

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df['population_in_millions'] = df['population'] / 1000000
print(df)

###Activity 11: Reordering Columns

**Change Column Order:**
Reorder columns by reassigning the DataFrame with columns in the desired order.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df = df[['population', 'city']]
print(df)

###Activity 12: Dropping Columns

**Drop a Single Column:**
Use `df.drop(columns=['column_name'])` to drop a single column.

In [ ]:

df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df = df.drop(columns=['population'])
print(df)

**Drop Multiple Columns:**
Pass multiple column names to the columns argument to drop multiple columns.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

df = df.drop(columns=['city', 'population'])
print(df)

### Activity 12: Adding New Columns

**Append a New Column:**
Add a new column by creating a Series and assigning it to the DataFrame.

In [ ]:
df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

states = pd.Series(['NY', 'CA', 'IL'])
df['state'] = states
print(df)

### Activity 13: Inserting Columns at Specific Positions

**Insert a Column at a Specific Position:**
Use `df.insert(position, column_name, data)` to insert a column at a specific position.

In [ ]:

df = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'population': [8175133, 3792621, 2695598]
})

gender = pd.Series(['female', 'male', 'male'])
position = 1
column_name = 'gender'

df.insert(position, column_name, gender)
print(df)