<a href="https://colab.research.google.com/github/poudyaldiksha/Data-Science-project/blob/main/Lesson_22_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 22: Time Series Data III

The process of cleaning data varies depending on the specific dataset you're working with. Nonetheless, the methods and steps used to clean a DataFrame are generally consistent.

In [ ]:

#Mounting the google drive
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
# Last class activity


# Import the required modules and load the time-series dataset on air quality
import pandas as pd

air_df=pd.read_csv("/content/drive/MyDrive/datasets/AirQualityUCI.csv", sep=";")
air_df.head()

# Removing the 'Unnamed: 15' & 'Unnamed: 16' columns.
air_df = air_df.drop(columns=['Unnamed: 15', 'Unnamed: 16'], axis=1)

# Removing the null values.
air_df = air_df.dropna()

# Creating a Pandas series containing 'datetime' objects.
time = []
for i in air_df["Time"]:
    time.append(i.replace(".",":"))

time_s = pd.Series(time)
time_s

date_time = air_df["Date"] + " " + time_s

#Convert to datetime values
date_time = pd.to_datetime(date_time, format="%d/%m/%Y %H:%M:%S")


# Remove the Date & Time columns from the DataFrame and add the 'date_time' series in it.
air_df = air_df.drop(columns=['Date', 'Time'], axis=1)
air_df.insert(loc=0, column='DateTime', value=date_time)



# Get the Pandas series containing the year values as integers.
year_series = date_time.dt.year

# Get the Pandas series containing the month values as integers.
month_series = date_time.dt.month

# Get the Pandas series containing the day values as integers.
day_series = date_time.dt.day

# Get the Pandas series containing the days of a week, i.e., Monday, Tuesday, Wednesday etc.
day_name_series = date_time.dt.day_name()

# Add the 'Year', 'Month', 'Day' and 'Day Name' columns to the DataFrame.
air_df['Year'] = year_series
air_df['Month'] = month_series
air_df['Day'] = day_series
air_df['Day Name'] = day_name_series

# Sort the DataFrame by the 'DateTime' values in the ascending order.
air_df = air_df.sort_values(by='DateTime')

air_df.head()

,DateTime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
0,2004-03-10 18:00:00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",2004,3,10,Wednesday
1,2004-03-10 19:00:00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",2004,3,10,Wednesday
2,2004-03-10 20:00:00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",2004,3,10,Wednesday
3,2004-03-10 21:00:00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",2004,3,10,Wednesday
4,2004-03-10 22:00:00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",2004,3,10,Wednesday

### Activity 1: commas to dot replacement

The  values in the `CO(GT), C6H6(GT), T,	RH` and	`AH` columns contain the commas in them. Let's replace the commas with periods (or dots).

In [ ]:
#replace the commas with periods in a Pandas series.
def replace_comma(b):
    list1 = []
    for i in b:
        list1.append(float(str(i).replace(",",".")))
    return pd.Series(list1)

In [ ]:
#Apply the 'replace_comma()' function on the ''CO(GT)', 'C6H6(GT)', 'T', 'RH' and 'AH' columns.
list2 = ['CO(GT)', 'C6H6(GT)', 'T', 'RH', 'AH' ]
for i in list2:

    air_df[i] = replace_comma(air_df[i])

Let's also print the information on the `df` DataFrame. Except for the first column and the last column, all other columns must have the numeric (`float` or `int`) data-type values.

In [ ]:
# Print the information of the DataFrame.
air_df.info()

---

### Acitivity 2: What are Garbage Values?

In [ ]:
#  Get the descriptive statistics for all the numeric data-type columns.
air_df.describe()

,DateTime,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day
count,9357,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,2004-09-21 16:00:00,-34.207524,1048.990061,-159.090093,1.865683,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,9.778305,39.485380,-6.837604,2004.240141,6.310356,15.876884
min,2004-03-10 18:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,2004.000000,1.000000,1.000000
25%,2004-06-16 05:00:00,0.600000,921.000000,-200.000000,4.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,10.900000,34.100000,0.692300,2004.000000,3.000000,8.000000
50%,2004-09-21 16:00:00,1.500000,1053.000000,-200.000000,7.900000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,17.200000,48.600000,0.976800,2004.000000,6.000000,16.000000
75%,2004-12-28 03:00:00,2.600000,1221.000000,-200.000000,13.600000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,24.100000,61.900000,1.296200,2004.000000,9.000000,23.000000
max,2005-04-04 14:00:00,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,2005.000000,12.000000,31.000000
std,NaN,77.657170,329.832710,139.789093,41.380206,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,43.203623,51.216145,38.976670,0.427192,3.438160,8.808653



Now, let's remove all the columns from the  DataFrame containing more than 10% garbage value.

**Key Points:**

- **Garbage Values:** Data points in a DataFrame column that are invalid, meaningless, or misleading.

- **Identification:** Look for outliers, unexpected categories, or unusual text patterns.
Handling Strategies:

- **Removal:** Common for columns with high garbage value percentage (e.g., > 10%). Consider impact on analysis before removing.

- **Imputation:** Replace missing values with estimated values (mean, median, KNN).

- **Encoding:**Convert missing values into a separate category.

- **10% Rule:** A general guideline to consider removing columns with more than 10% garbage values.

**Choosing the Right Approach:**
1. Consider impact on analysis, importance of the column, and domain knowledge.
2. Explore different strategies (removal, imputation, encoding) and their effects.
3. Document your data cleaning process.


**Remember:** The 10% rule is a starting point, not a strict rule. Use it in conjunction with other factors to make informed decisions about handling garbage values in data science.

In [ ]:
# Remove all the columns from the DataFrame containing more than 10% garbage value.
a = ['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)',
       'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)',
       'T', 'RH', 'AH']
for i in a:
    print(i, air_df[air_df[i] == -200].shape[0])

CO(GT) 1683
PT08.S1(CO) 366
NMHC(GT) 8443
C6H6(GT) 366
PT08.S2(NMHC) 366
NOx(GT) 1639
PT08.S3(NOx) 366
NO2(GT) 1642
PT08.S4(NO2) 366
PT08.S5(O3) 366
T 366
RH 366
AH 366

In [ ]:
# percentage number of garbage values in all columns
for i in air_df.columns[1:-4]:
    print(i,round((air_df[air_df[i] == -200].shape[0]/ air_df.shape[0]) * 100,2))

CO(GT) 17.99
PT08.S1(CO) 3.91
NMHC(GT) 90.23
C6H6(GT) 3.91
PT08.S2(NMHC) 3.91
NOx(GT) 17.52
PT08.S3(NOx) 3.91
NO2(GT) 17.55
PT08.S4(NO2) 3.91
PT08.S5(O3) 3.91
T 3.91
RH 3.91
AH 3.91

In [ ]:
#remove garbage values more than 10%
garbage = ["CO(GT)","NMHC(GT)","NOx(GT)","NO2(GT)"]
air_df.drop(garbage, axis =1 ,inplace= True)

In [ ]:
air_df

,DateTime,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
0,2004-03-10 18:00:00,1360.0,11.9,1046.0,1056.0,1692.0,1268.0,13.6,48.9,0.7578,2004,3,10,Wednesday
1,2004-03-10 19:00:00,1292.0,9.4,955.0,1174.0,1559.0,972.0,13.3,47.7,0.7255,2004,3,10,Wednesday
2,2004-03-10 20:00:00,1402.0,9.0,939.0,1140.0,1555.0,1074.0,11.9,54.0,0.7502,2004,3,10,Wednesday
3,2004-03-10 21:00:00,1376.0,9.2,948.0,1092.0,1584.0,1203.0,11.0,60.0,0.7867,2004,3,10,Wednesday
4,2004-03-10 22:00:00,1272.0,6.5,836.0,1205.0,1490.0,1110.0,11.2,59.6,0.7888,2004,3,10,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,2005-04-04 10:00:00,1314.0,13.5,1101.0,539.0,1374.0,1729.0,21.9,29.3,0.7568,2005,4,4,Monday
9353,2005-04-04 11:00:00,1163.0,11.4,1027.0,604.0,1264.0,1269.0,24.3,23.7,0.7119,2005,4,4,Monday
9354,2005-04-04 12:00:00,1142.0,12.4,1063.0,603.0,1241.0,1092.0,26.9,18.3,0.6406,2005,4,4,Monday
9355,2005-04-04 13:00:00,1003.0,9.5,961.0,702.0,1041.0,770.0,28.3,13.5,0.5139,2005,4,4,Monday
9356,2005-04-04 14:00:00,1071.0,11.9,1047.0,654.0,1129.0,816.0,28.5,13.1,0.5028,2005,4,4,Monday

### Activity 3: The `loc[]` Function

 The `loc[]` function from Pandas library  is an extension to the `iloc[]` function. The `iloc[]` function takes only the row and column indices as inputs. But in addition to the row and column indices, the `loc[]` function also accepts the array of row indices and column indices as inputs. It also accepts the specific column names as inputs.


### Using the loc Function in Pandas:

The `loc` function in Pandas is used to access a group of rows and columns by labels or a boolean array. It’s an incredibly versatile function for data manipulation and selection.

In [ ]:
# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [ ]:
df.shape

(5, 3)

In [ ]:
df.iloc[[3,4], [1,2]]

   Age     City
3   32  Houston
4   29  Phoenix

In [ ]:
df.iloc[[3,4],1:3]

   Age     City
3   32  Houston
4   29  Phoenix

In [ ]:
df.loc[[3,4],["Age","City"]]

   Age     City
3   32  Houston
4   29  Phoenix

**Selecting Rows**
You can use `loc` to select rows based on labels. For example, to select the row where the label is 2:

In [ ]:
# Activity: Selecting rows
df.loc[2]

Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

**Selecting Columns**
To select specific columns, you can pass the column names:

In [ ]:
# Select the 'Name' and 'Age' columns

df.loc[1,["Name","Age"]]

Name    Bob
Age      27
Name: 1, dtype: object

In [ ]:
df.iloc[:,:2]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32
4      Eve   29

**Selecting a Subset of Rows and Columns**
You can also select a subset of rows and columns:

In [ ]:
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [ ]:
df.iloc[1:4,[0,2]]

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [ ]:
# Select rows with index labels 1 to 3 and columns 'Name' and 'City'
df.loc[1:4,["Name","City"]]

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

In [ ]:
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [ ]:
df.loc[[1,4],["Name"]]

  Name
1  Bob
4  Eve

In [ ]:
df

In [ ]:
df.iloc[1:5,[0,2]]

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

**Conditional Selection**
Using `loc`, you can filter rows based on a condition:

In [ ]:
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [ ]:
# Select rows where the Age is greater than 25
df.loc[(df["Age"]> 25) & (df["Age"]<30)]

  Name  Age         City
1  Bob   27  Los Angeles
4  Eve   29      Phoenix

**Difference Between loc and iloc**
- `loc`: Selects data by labels (index or column names).
- `iloc`: Selects data by integer-location based indexing.

In [ ]:
# Select the row at index position 2

df.iloc[2]

Name    Charlie
Age          22
City    Chicago
Name: 2, dtype: object

In [ ]:
pd.Series([1,2,3,4,5]).describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
pd.Series([1,2,3,4,5,-200,-200,-200]).describe()

count      8.00000
mean     -73.12500
std      105.06928
min     -200.00000
25%     -200.00000
50%        1.50000
75%        3.25000
max        5.00000
dtype: float64

In [ ]:
# Select the first two columns of the first three rows
df.iloc[:3,:2]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

Calculate Median values for 2004 and 2005 years

In [ ]:
air_df["Year"].value_counts()

Year
2004    7110
2005    2247
Name: count, dtype: int64

In [ ]:
air_df.columns

Index(['DateTime', 'PT08.S1(CO)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'PT08.S3(NOx)',
       'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH', 'Year', 'Month', 'Day',
       'Day Name'],
      dtype='object')

In [ ]:
# Calculate the median values for the columns having indices between 1 and -4 (excluding -4) for the year 2004.
air_df.loc[air_df["Year"] == 2004, air_df.columns[1:14]].describe()

,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day
count,7110.000000,7110.000000,7110.00000,7110.000000,7110.000000,7110.000000,7110.000000,7110.000000,7110.000000,7110.0,7110.000000,7110.000000
mean,1055.135443,3.876779,923.60661,822.454571,1495.659353,973.985513,13.779001,40.292053,-5.310343,2004.0,7.648101,16.146835
std,314.719517,37.859514,332.55071,315.705690,433.109562,434.094624,39.705743,46.983126,35.441047,0.0,2.801381,8.757552
min,-200.000000,-200.000000,-200.00000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,2004.0,3.000000,1.000000
25%,919.000000,4.600000,741.00000,666.000000,1331.250000,712.000000,14.300000,33.000000,0.855925,2004.0,5.000000,9.000000
50%,1052.000000,8.600000,923.00000,815.000000,1528.000000,933.000000,20.150000,47.700000,1.083550,2004.0,8.000000,16.000000
75%,1221.000000,14.200000,1124.00000,982.000000,1726.000000,1233.750000,25.800000,61.000000,1.404175,2004.0,10.000000,24.000000
max,2040.000000,63.700000,2214.00000,2683.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,2004.0,12.000000,31.000000

In [ ]:
# Calculate the median values for the columns  for the year 2005.
air_df.loc[air_df['Year'] == 2005, air_df.columns[1:-4]].describe()

,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
count,2247.000000,2247.000000,2247.000000,2247.000000,2247.000000,2247.000000,2247.000000,2247.000000,2247.000000
mean,1029.544726,-4.497864,802.797063,708.086782,1061.832221,978.510013,-2.880774,36.932888,-11.670190
std,373.059005,50.426047,356.435107,326.303957,415.312391,522.776411,50.737736,62.700754,48.186199
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,925.500000,2.900000,643.500000,553.500000,906.000000,641.000000,4.700000,37.200000,0.413350
50%,1055.000000,5.800000,805.000000,721.000000,1084.000000,973.000000,8.600000,50.900000,0.596400
75%,1222.000000,11.200000,1021.500000,893.500000,1297.000000,1344.500000,13.400000,64.750000,0.804950
max,1846.000000,43.000000,1831.000000,1881.000000,2147.000000,2494.000000,30.000000,86.600000,1.393000

As we can see, the median values for 2004 and 2005 are different. Hence, we should split the DataFrame into two different DataFrames.
-  One for 2004 datapoints and another for 2005 datapoints.

---

### Activity 4: Dataframe split by year column

In [ ]:
air_df

In [ ]:
#Count the number of rows containing '2004' and '2005' year values.
air_df.shape

(9357, 14)

In [ ]:
air_df["Year"].value_counts()

Year
2004    7110
2005    2247
Name: count, dtype: int64

In [ ]:
air_df[air_df["Month"] == 5]

,DateTime,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
1230,2004-05-01 00:00:00,1425.0,15.2,1155.0,709.0,1936.0,1789.0,17.8,66.8,1.3460,2004,5,1,Saturday
1231,2004-05-01 01:00:00,1179.0,9.3,951.0,826.0,1724.0,1323.0,17.3,68.3,1.3346,2004,5,1,Saturday
1232,2004-05-01 02:00:00,1047.0,6.5,833.0,939.0,1647.0,1081.0,16.5,70.2,1.3099,2004,5,1,Saturday
1233,2004-05-01 03:00:00,1009.0,6.3,825.0,950.0,1629.0,938.0,15.7,73.1,1.2902,2004,5,1,Saturday
1234,2004-05-01 04:00:00,882.0,3.5,685.0,1134.0,1492.0,673.0,16.2,69.9,1.2756,2004,5,1,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1969,2004-05-31 19:00:00,1124.0,16.6,1199.0,794.0,1858.0,1101.0,24.5,37.7,1.1454,2004,5,31,Monday
1970,2004-05-31 20:00:00,1020.0,10.7,1003.0,904.0,1716.0,916.0,21.7,46.9,1.2044,2004,5,31,Monday
1971,2004-05-31 21:00:00,1035.0,7.5,878.0,977.0,1694.0,825.0,19.3,68.8,1.5190,2004,5,31,Monday
1972,2004-05-31 22:00:00,986.0,5.3,781.0,1063.0,1633.0,693.0,17.6,81.6,1.6296,2004,5,31,Monday
1973,2004-05-31 23:00:00,1017.0,6.5,834.0,986.0,1676.0,734.0,17.8,80.3,1.6212,2004,5,31,Monday

In [ ]:
air_df["Month"].value_counts()

Month
3     1254
4      807
5      744
7      744
8      744
10     744
12     744
1      744
6      720
9      720
11     720
2      672
Name: count, dtype: int64

In [ ]:
air_df[air_df["Year"]==2004]

,DateTime,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
0,2004-03-10 18:00:00,1360.0,11.9,1046.0,1056.0,1692.0,1268.0,13.6,48.9,0.7578,2004,3,10,Wednesday
1,2004-03-10 19:00:00,1292.0,9.4,955.0,1174.0,1559.0,972.0,13.3,47.7,0.7255,2004,3,10,Wednesday
2,2004-03-10 20:00:00,1402.0,9.0,939.0,1140.0,1555.0,1074.0,11.9,54.0,0.7502,2004,3,10,Wednesday
3,2004-03-10 21:00:00,1376.0,9.2,948.0,1092.0,1584.0,1203.0,11.0,60.0,0.7867,2004,3,10,Wednesday
4,2004-03-10 22:00:00,1272.0,6.5,836.0,1205.0,1490.0,1110.0,11.2,59.6,0.7888,2004,3,10,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7105,2004-12-31 19:00:00,930.0,5.3,781.0,933.0,906.0,866.0,9.3,33.6,0.3958,2004,12,31,Friday
7106,2004-12-31 20:00:00,962.0,5.3,780.0,919.0,909.0,884.0,9.6,32.3,0.3871,2004,12,31,Friday
7107,2004-12-31 21:00:00,974.0,5.5,790.0,915.0,895.0,951.0,9.1,32.5,0.3766,2004,12,31,Friday
7108,2004-12-31 22:00:00,1055.0,5.6,791.0,845.0,936.0,1195.0,9.1,37.2,0.4310,2004,12,31,Friday
7109,2004-12-31 23:00:00,1003.0,4.6,744.0,882.0,899.0,1138.0,7.8,38.4,0.4085,2004,12,31,Friday

In [ ]:
# Create a new DataFrame containing records for the year 2004.

air_df_2004 = air_df[air_df["Year"]==2004]

air_df_2004

,DateTime,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
0,2004-03-10 18:00:00,1360.0,11.9,1046.0,1056.0,1692.0,1268.0,13.6,48.9,0.7578,2004,3,10,Wednesday
1,2004-03-10 19:00:00,1292.0,9.4,955.0,1174.0,1559.0,972.0,13.3,47.7,0.7255,2004,3,10,Wednesday
2,2004-03-10 20:00:00,1402.0,9.0,939.0,1140.0,1555.0,1074.0,11.9,54.0,0.7502,2004,3,10,Wednesday
3,2004-03-10 21:00:00,1376.0,9.2,948.0,1092.0,1584.0,1203.0,11.0,60.0,0.7867,2004,3,10,Wednesday
4,2004-03-10 22:00:00,1272.0,6.5,836.0,1205.0,1490.0,1110.0,11.2,59.6,0.7888,2004,3,10,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7105,2004-12-31 19:00:00,930.0,5.3,781.0,933.0,906.0,866.0,9.3,33.6,0.3958,2004,12,31,Friday
7106,2004-12-31 20:00:00,962.0,5.3,780.0,919.0,909.0,884.0,9.6,32.3,0.3871,2004,12,31,Friday
7107,2004-12-31 21:00:00,974.0,5.5,790.0,915.0,895.0,951.0,9.1,32.5,0.3766,2004,12,31,Friday
7108,2004-12-31 22:00:00,1055.0,5.6,791.0,845.0,936.0,1195.0,9.1,37.2,0.4310,2004,12,31,Friday
7109,2004-12-31 23:00:00,1003.0,4.6,744.0,882.0,899.0,1138.0,7.8,38.4,0.4085,2004,12,31,Friday

In [ ]:
# Calculate the number of rows and columns in the DataFrame for the 2004 year records.
air_df_2004.shape

(7110, 14)

In [ ]:
# Create a new DataFrame containing records for the year 2005.
air_df_2005 = air_df.loc[air_df['Year'] == 2005, air_df.columns]
air_df_2005.head()

,DateTime,PT08.S1(CO),C6H6(GT),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year,Month,Day,Day Name
7110,2005-01-01 00:00:00,1046.0,4.2,724.0,848.0,898.0,1201.0,8.2,40.1,0.4375,2005,1,1,Saturday
7111,2005-01-01 01:00:00,1275.0,8.8,930.0,649.0,1024.0,1617.0,5.3,50.7,0.4564,2005,1,1,Saturday
7112,2005-01-01 02:00:00,1173.0,7.5,878.0,738.0,1002.0,1355.0,5.9,50.0,0.4689,2005,1,1,Saturday
7113,2005-01-01 03:00:00,1163.0,7.6,881.0,748.0,1001.0,1296.0,4.9,53.9,0.4693,2005,1,1,Saturday
7114,2005-01-01 04:00:00,1054.0,5.6,791.0,830.0,967.0,1131.0,4.3,55.3,0.4650,2005,1,1,Saturday

In [ ]:
#Calculate the number of rows and columns in the DataFrame for the 2005
air_df_2005.shape

Now, let's replace the `-200` value with the median values

### Activity 5: Pandas `replace` vs. String `replace` function

**Pandas replace**
1. Context: Used with pandas DataFrames or Series.
2.  Purpose: Allows you to replace specific values in your DataFrame or Series. It can handle different data types, such as integers, floats, and strings.
3.  Usage:
     -  You can replace values across the entire DataFrame or Series.
     - Supports replacing multiple values at once using a dictionary.

In [ ]:
# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, -200, 4],
    'B': [5, -200, 7, 8]
})
df

     A    B
0    1    5
1    2 -200
2 -200    7
3    4    8

In [ ]:
# Replace -200 with 8.6 in the entire DataFrame
df = df.replace(-200, 8.6)
df

     A    B
0  1.0  5.0
1  2.0  8.6
2  8.6  7.0
3  4.0  8.0

- The replace function is called directly on the DataFrame object.
- There is no need to prefix it with `pd. `because you are calling it as a method on a DataFrame which is an object of the pandas library.
- The same principle applies to other DataFrame methods, such as `drop`, `rename`, etc. These methods are designed to be used directly on DataFrame or Series objects once pandas is imported.

**String replace**
1. Context: Used with string objects in Python.
2. Purpose: Replaces specified substrings in a string with another substring.
3. Usage:
    - Applies only to string objects and is used to modify text content.
    - Does not handle data structures like DataFrames or Series.

In [ ]:
a = ["1.2" ,"2.3"]
b =[]
for i in a:
    b.append(str(i).replace(".",","))
print(b)

['1,2', '2,3']

In [ ]:
"hello.....".replace(".",",")

'hello,,,,,'

In [ ]:
# Replace 'world' with 'Python' in a string
text = "Hello, world!"
new_text = text.replace('world', 'Python')
print(new_text)

Hello, Python!

**Key Differences**
1. Data Type:

  - Pandas replace: Operates on pandas DataFrames or Series, which are data structures containing potentially mixed data types.
  - String replace: Operates on string objects, which are sequences of characters.
2. Functionality:

 -  Pandas replace: Can replace values across an entire DataFrame or Series, and can handle various data types (e.g., integers, floats, strings).
 - String replace: Replaces parts of the text within a single string, only applicable to strings.

 **Summary**
- Use pandas replace when you need to modify values within pandas DataFrames or Series.
- Use string replace when you need to modify specific parts of a text within a string.

### Activity 6: Garbage Value Replacement

**Why Replace Garbage Values with the Median?**

When working with data, it's common to encounter "garbage values," which can be missing, invalid, or extreme outliers that don't represent real-world phenomena. Cleaning such data is crucial for accurate analysis and modeling. One common strategy is to replace these garbage values with the median. Here’s why the median is often preferred:

**When to Use the Median for Imputation**
- When Data is Skewed: If the data distribution is skewed, the median provides a better central value than the mean.
- When Outliers are Present: In the presence of outliers, the median is more robust and less influenced by extreme values.
- For Small Datasets: In smaller datasets, the median can be a reliable measure to replace garbage values without introducing significant bias.

In [ ]:

# Example data with an outlier
data = {'values': [1, 2, 3, 4, 100]}
df = pd.DataFrame(data)

# Calculate the mean and median
mean_value = df['values'].mean()
median_value = df['values'].median()

print(f"Mean: {mean_value}, Median: {median_value}")

Mean: 22.0, Median: 3.0

In [ ]:
a = pd.Series([1,2,3,4,5])
a.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [ ]:
b = pd.Series([1,2,3,4,5,100,100,100,100,100])
b.describe()

count     10.000000
mean      51.500000
std       51.134355
min        1.000000
25%        3.250000
50%       52.500000
75%      100.000000
max      100.000000
dtype: float64

In this case, the mean is heavily influenced by the outlier `(100)`, while the median `(3)` represents the central tendency of the data more accurately.

In [ ]:
air_df_2004["T"].median()

20.15

In [ ]:
air_df_2004["T"].replace(-200,20.15)

0       13.6
1       13.3
2       11.9
3       11.0
4       11.2
        ...
7105     9.3
7106     9.6
7107     9.1
7108     9.1
7109     7.8
Name: T, Length: 7110, dtype: float64

In [ ]:
air_df_2004.columns[1:-4]

In [ ]:
# Replace the -200 value with the median values for the 2004 year DataFrame.
for i in air_df_2004.columns[1:-4]:
    median = air_df_2004[i].median()
    air_df_2004[i] = air_df_2004[i].replace( -200, value=median)

<ipython-input-103-737a0e750213>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  air_df_2004[i] = air_df_2004[i].replace( -200, value=median)

In [ ]:
# Repeat the same for the 2005 year DataFrame.
for i in air_df_2005.columns[1:-4]:
    median = air_df_2005[i].median()
    air_df_2005[i] = air_df_2005[i].replace(to_replace = -200, value=median)

Now, let's again, calculate the number of rows containing '-200' in each column except for the `DateTime, Year, Month` and `Day` columns in both the DataFrames.

In [ ]:
# Compute the number of rows containing '-200' in each column in the 2004 year DataFrame.
for i in air_df_2004.columns[1:-4]:
 print(i, air_df_2004[air_df_2004[i] == -200].shape[0])

PT08.S1(CO) 0
C6H6(GT) 0
PT08.S2(NMHC) 0
PT08.S3(NOx) 0
PT08.S4(NO2) 0
PT08.S5(O3) 0
T 0
RH 0
AH 0

### Activity 7: The `groupby()`  Function


The groupby function in pandas allows you to group rows in a DataFrame based on the values in one or more columns. Once grouped, you can perform various operations on each group independently, such as calculating averages, sums, or counts.


To group the values of a DataFrame by a particular value, use the `groupby()` function.

**Syntax:** `dataframe.groupby(by='column')`

You can additionally set the `sort` parameter either equal to `True` or `False` depending on whether you want to sort the values or not. By default, the `groupby()` function returns a new Pandas `DataFrameGroupBy` object containing the grouped sorted values.

In [ ]:
# Create a DataFrame
data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'West'],
    'Sales': [200, 150, 180, 120, 250, 300]
}

df = pd.DataFrame(data)
df

  Region  Sales
0  North    200
1  South    150
2  North    180
3  South    120
4   East    250
5   West    300

In [ ]:
# Group by 'Region' and calculate the sum of sales in each region
grouped_df = df.groupby('Region')
grouped_df

The `group_by()` function returns a `DataFrameGroupBy` object with its physical memory location.


**The `get_group()` Function**

To get all the occurrences of a value from a group, use the `get_group()` function.

**Syntax:** `DataFrameGroupBy_object.get_group(item)`

In [ ]:
# Get all the records for North.
grouped_df.get_group("North")

  Region  Sales
0  North    200
2  North    180

In [ ]:
df.groupby("Region").get_group("North").sum()

Region    NorthNorth
Sales            380
dtype: object

In [ ]:
# Group by 'Region' and calculate the sum of sales in each region
groupsales_df = df.groupby('Region').sum()
groupsales_df

        Sales
Region
East      250
North     380
South     270
West      300

### Activity 8: The `agg()` Function

 The aggregation functions are `count(), sum(), min(), max(), mean()` etc.


Instead of applying the aggregation functions on a `DataFrameGroupBy` object individually, you can apply them together using the `agg()` function. Inside the `agg()` function, you have to pass the names of the functions (as string values) as inputs.


The agg function in pandas is used to perform multiple aggregation operations on a DataFrame or Series after grouping data with the groupby function. It provides a flexible way to apply various aggregation functions to different columns, which can be useful for summarizing and analyzing data.



**Syntax:** `df.groupby('column_name').agg({'column1': 'agg_function1', 'column2': 'agg_function2'})`

In [ ]:
# Create a DataFrame
data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'West'],
    'Sales': [200, 150, 180, 120, 250, 300],
    'Profit': [50, 30, 40, 20, 70, 90]
}

df = pd.DataFrame(data)
df

  Region  Sales  Profit
0  North    200      50
1  South    150      30
2  North    180      40
3  South    120      20
4   East    250      70
5   West    300      90

In [ ]:
# Create a DataFrame
data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'West'],
    'Sales': [200, 150, 180, 120, 250, 300],
    'Profit': [50, 30, 40, 20, 70, 90]
}

df = pd.DataFrame(data)

# Group by 'Region' and calculate the sum of sales and the average profit
grouped_df = df.groupby('Region').agg({'Sales': 'sum', 'Profit': 'mean'})

print(grouped_df)

        Sales  Profit
Region
East      250    70.0
North     380    45.0
South     270    25.0
West      300    90.0

### Activity 9: The `groupby()` Function on data set

let's group all the values by months

In [ ]:
air_df_2004

In [ ]:

# Group the records for the 2004 DataFrame by month.
group_2004_month =air_df_2004.groupby(by="Month")
group_2004_month

In [ ]:

# Get all the records for the month of March.
group_2004_month.get_group(3)

In [ ]:
# Group the records for the 2005 by month.
group_2005_month = air_df_2005.groupby(by='Month')
group_2005_month

---

---

### Activity 10: The `agg()` Function on data set



The agg function in pandas is used to perform multiple aggregation operations on a DataFrame or Series after grouping data with the groupby function. It provides a flexible way to apply various aggregation functions to different columns, which can be useful for summarizing and analyzing data.



**Syntax:** `df.groupby('column_name').agg({'column1': 'agg_function1', 'column2': 'agg_function2'})`

You can also provide the name of the functions to be applied as items in a list.

In [ ]:
# Activity
group_2004_month.agg(func={"T": ["mean","std","median"],
                         "AH" :"max",
                          "Month":"count",
                          "RH": ["min","max"]})

---

---

### Activity 11: Multivariate Grouping & Aggregation

We can also group multiple columns at once by passing a list of columns to be grouped.

 **Grouping by Multiple Columns**

 You can also group by more than one column. For example, suppose we have data on sales and profits by both region and product type:

In [ ]:
# Create a DataFrame
data = {
    'Region': ['North', 'South', 'North', 'South', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'B', 'A', 'A', 'B', 'B', 'A'],
    'Sales': [200, 150, 180, 120, 250, 300, 160, 190],
    'Profit': [50, 30, 40, 20, 70, 90, 60, 80]
}

df = pd.DataFrame(data)

# Group by 'Region' and 'Product' and calculate the sum of sales and average profit
grouped_df = df.groupby(['Region', 'Product']).agg({'Sales': 'sum', 'Profit': 'mean'})

print(grouped_df)


Let's group the DataFrames about the `Month` & `Day Name` columns.

In [ ]:
# Group the DataFrame for the year 2004 about the 'Month' & 'Day Name' columns.
group_2004_multi = air_df_2004.groupby(by=["Month","Day Name"])

Let's get the count of each day for each month in 2004.

In [ ]:
# Get the count of each day for each month in 2004.
group_2004_multi.count()

Let's get all the records for all Mondays in the month of March, 2004.

**Note:** The values to be retrieved should be passed as a tuple in the same order of grouping.

In [ ]:
#  Get all the records for all Mondays in the month of March3, 2004.
group_2004_multi.get_group((3,"Monday"))

www.kaggle.com